name: CI/CD Pipeline
on: [push, pull_request]

jobs:
  quality-and-docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install Linting tools
      run: |
        pip install ruff

    - name: Run Ruff Check (Linting)
      run: ruff check .

    - name: Build Docker Image
      run: |
        docker build -t analyse-compta:${{ github.sha }} .

    - name: Test API
  run: |
    docker run -d -p 8000:8000 --name test_api analyse-compta:${{ github.sha }}

    # attendre que l'API soit prête (max 30s)
    for i in {1..30}; do
      if curl -s http://localhost:8000/docs > /dev/null; then
        echo "API is up"
        break
      fi
      sleep 1
    done

    # test final
    curl -f http://localhost:8000/docs

    docker stop test_api